sudo: required

language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-integration.txt
  - pip install -r requirements-unit.txt

run_app:
  - python3 -m flask run

script:
  - python integration_test/test_example.py
