sudo: required

language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-integration.txt
  - pip install -r requirements-unit.txt

script:
  - export SQLALCHEMY_DATABASE_URI='sqlite:///web.db'
  - pytest unit_test
  - python -m unittest discover -v
