version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run:
          name: "launch flask app"
          command: |
            python -m flask run
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build